apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
    app: dep1
spec:
  replicas: 2
  selectors:
    matchLabels:  
      app: dep1
  template:
    labels:
      app: dep1
    spec:
      containers:
      - name: c1
        image: R_IMAGE      